package com.papi.nova.binding.crypto

import android.content.Context
import android.content.ContextWrapper
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import java.io.File
import java.security.interfaces.RSAPrivateKey
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * The pairing certificate is generated by BouncyCastle on the real device, and a
 * broken generator only shows up as a host that refuses to pair. These run against
 * a scratch files directory so the device's own client.crt is never touched.
 */
@RunWith(AndroidJUnit4::class)
class NovaClientCertificateInstrumentationTest {
    private lateinit var scratch: File

    private class ScratchFilesContext(base: Context, private val dir: File) : ContextWrapper(base) {
        override fun getFilesDir(): File = dir
    }

    private fun provider(): AndroidCryptoProvider =
        AndroidCryptoProvider(ScratchFilesContext(InstrumentationRegistry.getInstrumentation().targetContext, scratch))

    @Before
    fun createScratchDirectory() {
        val parent = InstrumentationRegistry.getInstrumentation().targetContext.cacheDir
        scratch = File(parent, "crypto-test-" + System.nanoTime())
        assertTrue(scratch.mkdirs())
    }

    @After
    fun removeScratchDirectory() {
        scratch.deleteRecursively()
    }

    @Test
    fun generatesASigningCertificateAndKeyOnAFreshInstall() {
        val certificate = provider().clientCertificate

        assertNotNull(certificate)
        assertEquals("CN=NVIDIA GameStream Client", certificate.subjectX500Principal.name)
        assertEquals("SHA256withRSA", certificate.sigAlgName)
        certificate.checkValidity()
        // A self signed certificate that cannot verify against its own key would
        // pair once and then fail every challenge.
        certificate.verify(certificate.publicKey)
        assertTrue(File(scratch, "client.crt").exists())
        assertTrue(File(scratch, "client.key").exists())
    }

    @Test
    fun generatesATwoThousandFortyEightBitKeyThatMatchesTheCertificate() {
        val instance = provider()
        val key = instance.clientPrivateKey

        assertTrue(key is RSAPrivateKey)
        assertEquals(2048, (key as RSAPrivateKey).modulus.bitLength())
        assertEquals(key.modulus, (instance.clientCertificate.publicKey as java.security.interfaces.RSAPublicKey).modulus)
    }

    @Test
    fun writesAPemCertificateAndReadsTheSameOneBackOnTheNextLaunch() {
        val first = provider()
        val pem = String(first.pemEncodedClientCertificate, Charsets.UTF_8)

        assertTrue(pem.startsWith("-----BEGIN CERTIFICATE-----"))
        assertTrue(pem.trimEnd().endsWith("-----END CERTIFICATE-----"))

        val second = provider()
        assertEquals(first.clientCertificate, second.clientCertificate)
        assertEquals(first.clientPrivateKey, second.clientPrivateKey)
    }
}
